; ============================================================
; PlatformIO Project Configuration
; Proyecto: Telemetría dual DS18B20 + Control LEDs vía MQTT TLS
; Autor: Luis Agreda | UMSS | xonar.site
; ============================================================

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 📦 Librerías
lib_deps =
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.9.0
    knolleary/PubSubClient@^2.8

; 🛠️ Optimizaciones de compilación
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DMQTT_MAX_PACKET_SIZE=512

; 📺 Filtros de monitor serial
monitor_filters =
    esp32_exception_decoder
    time
